version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to AWS ECR..."
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 091846656105.dkr.ecr.us-west-1.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t cicd-ecs-app .
      - docker tag cicd-ecs-app:latest 091846656105.dkr.ecr.us-west-1.amazonaws.com/cicd-ecs-app:latest
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 091846656105.dkr.ecr.us-west-1.amazonaws.com/cicd-ecs-app:latest
artifacts:
  files:
    - '**/*'